### ISSUE TITLE
Donation Tracker - Player end not working

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#102]
Relates to #96
had a player character try to use Actor struios, we have Donation tracker enabled. 

all the races were visable to them, even the ones outside designated folders (almost like the settings were not server wide and instead local for some reason)

And when they tryed to make a checracter, it created the actor and did not open the advancemt tab

exact same process worked for a GM account, just not player

**Comment by geoidesic** [comment]
I can't replicate this. Maybe give me the player login on your server and the exact type of character they were trying to create and I'll have a go.

**Comment by geoidesic** [comment]
## From Zarhog 
this bug is still prevelent, when a user has no permission level as in not in the data base as they havnt registered they have acess to everything.
![image](https://github.com/user-attachments/assets/1b1c1067-d756-4481-9a7b-0878f3510d09)
but if they are in the data base like shown
![image](https://github.com/user-attachments/assets/cfdd386c-284a-4663-8171-c0a77d464e02)
then they are limited to the folders
what will it take to resolve this as im 1 week away from enabling the character creation method on my server?
D&D 3.3.1
Foundry V12 330
Actor Stuido 1.5.7
ive only just now had the time to start testing 🙂
would appreciate the help 
(note: the intended effects should be that if user is not a GM and not in the data base they have access to only a specific folder, currently there is no way to designate a folder for someone that is not in the database)

**Comment by geoidesic** [comment]
I registered and logged in as Geo. Presumably this user is not in the database. Here are the races I have access to:
<img width="720" alt="Screenshot 2024-11-27 at 12 25 35" src="https://github.com/user-attachments/assets/2e0d61ed-aa0b-4bea-8e34-f3fdab7cb4db">

Next, I'll login as admin and see what's what there.

**Comment by geoidesic** [comment]
## More from Zarhog:
People not on the database need to be counted as "members"
so they can get acess to the base content
currently they are acessing all the content which is not wanted

**Comment by geoidesic** [comment]
Addressed in v1.5.8
Hopefully that does the job!
