### ISSUE TITLE
Leveling from 2 to 3 forces a 4th level up as well.

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#68]
AS-1.1.1
DnD5e-3.1.2
Foundry-11.315

https://github.com/user-attachments/assets/b8f06853-585f-41a2-af52-acb411e83b5c

**Comment by geoidesic** [comment]
This is not so simple. The problem is that the dnd5e system actually requires the class from the compendium, not the class as stored in the character. For some reason, the SRD classes, when added to the character, record their original compendium uuid in a flag: `item.flags.core.sourceId`. However, for the `AS-test` classes, that flag is missing.

@ChobitsCrazy maybe you can figure out why the `AS-test` classes are different in this way?

**Comment by geoidesic** [comment]
nvm... somehow that flag was there and now I can't find it again, so leave it with me
