### ISSUE TITLE
update modual to D&D 4x and provide small fix for 3.3.1

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#99]
![image](https://github.com/user-attachments/assets/ba9e5a23-d688-4300-a31e-e7d2e4127cd1)
![image](https://github.com/user-attachments/assets/d081055a-da89-4e26-8685-e7571724ffe0)
![image](https://github.com/user-attachments/assets/d9bf660a-78a0-44e2-a92c-2afafb3aa230)

Modual has some seeminly random behaviour in 3.3.1 where it will not always show the subclass option.

a small update for 3.3.1 to fix this bug is required
"if no subclasses are deteected, the subclass option should be skiped and hidden"
"if subclass is detected then it should be show"

in D&D V4.x they have added a field to determin at which level a subclass should be appiled 
for this the additional check of 
"if Level of Class < Subclass requirment, Do not show subclass, and skip"
"if Level of class => subclass requiremnt then show subclass"

**Comment by geoidesic** [comment]
I'm not able to replicate this. SRD cleric shows subclass, in both versions.
![Screenshot 2024-09-17 at 20 58 05](https://github.com/user-attachments/assets/137e32a7-bba5-4728-a21e-c463621ad4e6)
![Screenshot 2024-09-17 at 21 03 34](https://github.com/user-attachments/assets/047fcfda-b49b-43dc-8717-9c7db7ac1156)

What exactly are you trying to achieve? I'm not understanding what the problem is. Maybe provide the data that is causing the issue and give me a bit more to go on.

Actor studio doesn't decide whether to hide or show subclasses at different levels. That's not a feature it has currently, so if you wanted that it wouldn't be a bug-fix, it would be a new feature.

What it does currently is just this:
- When you select a class, it looks at the compendiums linked for SubClasses and it sees if any of those are listed by the selected class as being the registered subclass for that class.
- It does this by this conditional: `subClass.system.classIdentifier == characterClass.system.identifier`

If there's a match, it will show it, regardless of level. It doesn't care about the level for this.

**Comment by geoidesic** [comment]
The title is also a bit confusing. Please try to stick to one issue per issue – i.e. avoid the word "and".
You mention upgrade to 4.0.0 in the title but then you don't explain why that is necessary or what exactly needs to be upgraded that isn't working in that version.
Version 1.5.2 already works on dnd5e v4.0.1, so I'm not aware of any necessary upgrade. If there is something not working in that version, please raise a separate issue for it. 

Tx

**Comment by geoidesic** [comment]
I'm also not aware of any difference in behaviour between v4.0.0 and v3.3.1 wrt dnd5e and Actor Studio. It works in both, so I don't know what this extra field is to which you are referring that the dnd team told you about. I don't know what that is.

I think, if I read between the lines, that what you're actually asking for is a new feature – which is that the subclass select should be hidden if it has no options.

Does that sound correct?

**Comment by geoidesic** [comment]
But then I just tested that and it already does that. So, nope, I don't know what to do here.

**Comment by Zarhog** [comment]
Apoligies. please ignore this. 

it was a Captalisation error with "Cleric" and "cleric"
